import { AppTemplate } from './AppStore'

// Helper to create a standard linuxserver.io template
function lsio(id: string, name: string, icon: string, category: string, description: string, image: string, ports: Array<{containerPort: number; hostPort?: number; protocol: string}>, env: Array<{name: string; value?: string; description: string}> = [], volumes: Array<{containerPath: string; hostPath?: string; description: string}> = [], extra?: Partial<AppTemplate>): AppTemplate {
  return {
    id, name, icon, category, description,
    image: `linuxserver/${image}:latest`,
    version: 'latest',
    ports,
    environment: [
      { name: 'PUID', value: '1000', description: 'User ID' },
      { name: 'PGID', value: '1000', description: 'Group ID' },
      { name: 'TZ', value: 'America/Chicago', description: 'Timezone' },
      ...env,
    ],
    volumes: [
      { containerPath: '/config', hostPath: `/mnt/appdata/${id}`, description: 'Config directory' },
      ...volumes,
    ],
    restartPolicy: 'unless-stopped',
    ...extra,
  }
}

function simple(id: string, name: string, icon: string, category: string, description: string, image: string, ports: Array<{containerPort: number; hostPort?: number; protocol: string}>, env: Array<{name: string; value?: string; description: string}> = [], volumes: Array<{containerPath: string; hostPath?: string; description: string}> = [], extra?: Partial<AppTemplate>): AppTemplate {
  return {
    id, name, icon, category, description, image, version: 'latest',
    ports, environment: env, volumes,
    restartPolicy: 'unless-stopped',
    ...extra,
  }
}

export const APP_TEMPLATES: AppTemplate[] = [
  // ═══════════════════════════════════════
  // MEDIA
  // ═══════════════════════════════════════
  {
    id: 'plex', name: 'Plex Media Server', icon: '🎬', category: 'Media',
    description: 'Stream your personal media collection — movies, TV shows, music and photos',
    image: 'plexinc/pms-docker:latest', version: 'latest',
    ports: [{ containerPort: 32400, hostPort: 32400, protocol: 'tcp' }],
    environment: [
      { name: 'PUID', value: '1000', description: 'User ID' },
      { name: 'PGID', value: '1000', description: 'Group ID' },
      { name: 'VERSION', value: 'docker', description: 'Version tag' },
      { name: 'PLEX_CLAIM', value: '', description: 'Plex claim token from plex.tv/claim' },
    ],
    volumes: [
      { containerPath: '/config', hostPath: '/mnt/appdata/plex', description: 'Plex config & database' },
      { containerPath: '/tv', hostPath: '/mnt/media/tv', description: 'TV shows' },
      { containerPath: '/movies', hostPath: '/mnt/media/movies', description: 'Movies' },
      { containerPath: '/music', hostPath: '/mnt/media/music', description: 'Music' },
    ],
    restartPolicy: 'unless-stopped',
    resources: { cpuCores: 4, memoryMb: 2048 },
  },
  lsio('jellyfin', 'Jellyfin', '🎥', 'Media',
    'Free open-source media server — stream movies, TV, music and more',
    'jellyfin', [{ containerPort: 8096, hostPort: 8096, protocol: 'tcp' }], [],
    [
      { containerPath: '/data/tvshows', hostPath: '/mnt/media/tv', description: 'TV shows' },
      { containerPath: '/data/movies', hostPath: '/mnt/media/movies', description: 'Movies' },
    ]),
  lsio('emby', 'Emby', '📺', 'Media',
    'Personal media server with apps for every device',
    'emby', [{ containerPort: 8096, hostPort: 8097, protocol: 'tcp' }], [],
    [
      { containerPath: '/data/tvshows', hostPath: '/mnt/media/tv', description: 'TV shows' },
      { containerPath: '/data/movies', hostPath: '/mnt/media/movies', description: 'Movies' },
    ]),
  lsio('sonarr', 'Sonarr', '📡', 'Media',
    'Smart PVR for newsgroup and bittorrent users — automatically download TV shows',
    'sonarr', [{ containerPort: 8989, hostPort: 8989, protocol: 'tcp' }], [],
    [
      { containerPath: '/tv', hostPath: '/mnt/media/tv', description: 'TV shows' },
      { containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' },
    ]),
  lsio('radarr', 'Radarr', '🎞️', 'Media',
    'Movie collection manager — automatically download movies via Usenet and BitTorrent',
    'radarr', [{ containerPort: 7878, hostPort: 7878, protocol: 'tcp' }], [],
    [
      { containerPath: '/movies', hostPath: '/mnt/media/movies', description: 'Movies' },
      { containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' },
    ]),
  lsio('lidarr', 'Lidarr', '🎵', 'Media',
    'Music collection manager — automatically download music albums',
    'lidarr', [{ containerPort: 8686, hostPort: 8686, protocol: 'tcp' }], [],
    [
      { containerPath: '/music', hostPath: '/mnt/media/music', description: 'Music' },
      { containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' },
    ]),
  lsio('readarr', 'Readarr', '📚', 'Media',
    'Book and audiobook collection manager for Usenet and BitTorrent users',
    'readarr', [{ containerPort: 8787, hostPort: 8787, protocol: 'tcp' }], [],
    [
      { containerPath: '/books', hostPath: '/mnt/media/books', description: 'Books' },
      { containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' },
    ]),
  lsio('bazarr', 'Bazarr', '💬', 'Media',
    'Subtitle manager companion for Sonarr and Radarr',
    'bazarr', [{ containerPort: 6767, hostPort: 6767, protocol: 'tcp' }], [],
    [
      { containerPath: '/tv', hostPath: '/mnt/media/tv', description: 'TV shows' },
      { containerPath: '/movies', hostPath: '/mnt/media/movies', description: 'Movies' },
    ]),
  lsio('prowlarr', 'Prowlarr', '🔎', 'Media',
    'Indexer manager/proxy for the *arr stack — integrates with Sonarr, Radarr, Lidarr',
    'prowlarr', [{ containerPort: 9696, hostPort: 9696, protocol: 'tcp' }]),
  lsio('overseerr', 'Overseerr', '🎯', 'Media',
    'Request management and media discovery tool for Plex',
    'overseerr', [{ containerPort: 5055, hostPort: 5055, protocol: 'tcp' }]),
  lsio('tautulli', 'Tautulli', '📊', 'Media',
    'Monitor and track Plex Media Server activity and statistics',
    'tautulli', [{ containerPort: 8181, hostPort: 8181, protocol: 'tcp' }]),
  simple('sabnzbd', 'SABnzbd', '📥', 'Downloaders',
    'Free and easy binary newsreader for Usenet downloading',
    'linuxserver/sabnzbd:latest',
    [{ containerPort: 8080, hostPort: 8085, protocol: 'tcp' }],
    [{ name: 'PUID', value: '1000', description: 'User ID' }, { name: 'PGID', value: '1000', description: 'Group ID' }],
    [
      { containerPath: '/config', hostPath: '/mnt/appdata/sabnzbd', description: 'Config' },
      { containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' },
    ]),
  lsio('transmission', 'Transmission', '⬇️', 'Downloaders',
    'Lightweight, cross-platform BitTorrent client',
    'transmission', [{ containerPort: 9091, hostPort: 9091, protocol: 'tcp' }], [],
    [{ containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' }]),
  lsio('qbittorrent', 'qBittorrent', '🌊', 'Downloaders',
    'Feature-rich BitTorrent client with a web UI',
    'qbittorrent', [{ containerPort: 8080, hostPort: 8088, protocol: 'tcp' }], [],
    [{ containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' }]),
  lsio('nzbget', 'NZBGet', '📦', 'Downloaders',
    'Efficient Usenet downloader with optimized performance',
    'nzbget', [{ containerPort: 6789, hostPort: 6789, protocol: 'tcp' }], [],
    [{ containerPath: '/downloads', hostPath: '/mnt/downloads', description: 'Downloads' }]),

  // ═══════════════════════════════════════
  // GAME SERVERS
  // ═══════════════════════════════════════
  {
    id: 'pelican-panel', name: 'Pelican Panel', icon: '🦅', category: 'Game Servers',
    description: 'Game server management panel (successor to Pterodactyl) — manage Minecraft, Rust, ARK and more',
    image: 'ghcr.io/pelican-dev/panel:latest', version: 'latest',
    ports: [
      { containerPort: 80, hostPort: 8081, protocol: 'tcp' },
      { containerPort: 443, hostPort: 8444, protocol: 'tcp' },
    ],
    environment: [
      { name: 'APP_URL', value: 'http://localhost:8081', description: 'Panel URL' },
      { name: 'APP_TIMEZONE', value: 'America/Chicago', description: 'Timezone' },
      { name: 'DB_HOST', value: 'pelican-db', description: 'Database host' },
      { name: 'DB_PORT', value: '3306', description: 'Database port' },
      { name: 'DB_DATABASE', value: 'pelican', description: 'Database name' },
      { name: 'DB_USERNAME', value: 'pelican', description: 'Database user' },
      { name: 'DB_PASSWORD', value: '', description: 'Database password' },
      { name: 'CACHE_DRIVER', value: 'redis', description: 'Cache driver' },
      { name: 'REDIS_HOST', value: 'redis', description: 'Redis host' },
    ],
    volumes: [
      { containerPath: '/app/var/', hostPath: '/mnt/appdata/pelican/var', description: 'Panel data' },
      { containerPath: '/etc/nginx/http.d/default.conf', hostPath: '/mnt/appdata/pelican/nginx.conf', description: 'Nginx config' },
    ],
    restartPolicy: 'unless-stopped',
    resources: { cpuCores: 2, memoryMb: 1024 },
  },
  {
    id: 'pelican-wings', name: 'Pelican Wings', icon: '🪽', category: 'Game Servers',
    description: 'Pelican Wings daemon — runs game server instances (companion to Panel)',
    image: 'ghcr.io/pelican-dev/wings:latest', version: 'latest',
    ports: [
      { containerPort: 8080, hostPort: 8443, protocol: 'tcp' },
      { containerPort: 2022, hostPort: 2022, protocol: 'tcp' },
    ],
    environment: [],
    volumes: [
      { containerPath: '/etc/pelican', hostPath: '/mnt/appdata/pelican-wings/config', description: 'Wings config' },
      { containerPath: '/var/lib/pelican', hostPath: '/mnt/appdata/pelican-wings/data', description: 'Server data' },
      { containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' },
    ],
    restartPolicy: 'unless-stopped',
    resources: { cpuCores: 4, memoryMb: 4096 },
  },
  {
    id: 'pterodactyl-panel', name: 'Pterodactyl Panel', icon: '🦖', category: 'Game Servers',
    description: 'Open-source game server management panel — Minecraft, Rust, CS2, ARK, Valheim and more',
    image: 'ghcr.io/pterodactyl/panel:latest', version: 'latest',
    ports: [
      { containerPort: 80, hostPort: 8081, protocol: 'tcp' },
      { containerPort: 443, hostPort: 8444, protocol: 'tcp' },
    ],
    environment: [
      { name: 'APP_URL', value: 'http://localhost:8081', description: 'Panel URL' },
      { name: 'APP_TIMEZONE', value: 'America/Chicago', description: 'Timezone' },
      { name: 'DB_HOST', value: 'pterodactyl-db', description: 'Database host' },
      { name: 'DB_PORT', value: '3306', description: 'Database port' },
      { name: 'DB_DATABASE', value: 'pterodactyl', description: 'Database name' },
      { name: 'DB_USERNAME', value: 'pterodactyl', description: 'Database user' },
      { name: 'DB_PASSWORD', value: '', description: 'Database password' },
    ],
    volumes: [
      { containerPath: '/app/var/', hostPath: '/mnt/appdata/pterodactyl/var', description: 'Panel data' },
    ],
    restartPolicy: 'unless-stopped',
  },
  {
    id: 'minecraft', name: 'Minecraft Server', icon: '⛏️', category: 'Game Servers',
    description: 'Minecraft Java Edition server with automatic version management and plugin support',
    image: 'itzg/minecraft-server:latest', version: 'latest',
    ports: [{ containerPort: 25565, hostPort: 25565, protocol: 'tcp' }],
    environment: [
      { name: 'EULA', value: 'TRUE', description: 'Accept Minecraft EULA' },
      { name: 'TYPE', value: 'PAPER', description: 'Server type (VANILLA, PAPER, SPIGOT, FABRIC, FORGE)' },
      { name: 'MEMORY', value: '4G', description: 'Server memory allocation' },
      { name: 'MAX_PLAYERS', value: '20', description: 'Max players' },
      { name: 'DIFFICULTY', value: 'normal', description: 'Difficulty' },
      { name: 'MOTD', value: 'A Trakend OS Minecraft Server', description: 'Server MOTD' },
    ],
    volumes: [{ containerPath: '/data', hostPath: '/mnt/appdata/minecraft', description: 'Server data & worlds' }],
    restartPolicy: 'unless-stopped',
    resources: { cpuCores: 4, memoryMb: 4096 },
  },
  {
    id: 'minecraft-bedrock', name: 'Minecraft Bedrock', icon: '🪨', category: 'Game Servers',
    description: 'Minecraft Bedrock Edition dedicated server',
    image: 'itzg/minecraft-bedrock-server:latest', version: 'latest',
    ports: [{ containerPort: 19132, hostPort: 19132, protocol: 'udp' }],
    environment: [
      { name: 'EULA', value: 'TRUE', description: 'Accept EULA' },
      { name: 'SERVER_NAME', value: 'Trakend Bedrock Server', description: 'Server name' },
      { name: 'GAMEMODE', value: 'survival', description: 'Game mode' },
      { name: 'DIFFICULTY', value: 'normal', description: 'Difficulty' },
    ],
    volumes: [{ containerPath: '/data', hostPath: '/mnt/appdata/minecraft-bedrock', description: 'Server data' }],
    restartPolicy: 'unless-stopped',
    resources: { cpuCores: 2, memoryMb: 2048 },
  },
  simple('valheim', 'Valheim Server', '⚔️', 'Game Servers',
    'Dedicated Valheim server with auto-updates and backup support',
    'lloesche/valheim-server:latest',
    [{ containerPort: 2456, hostPort: 2456, protocol: 'udp' }, { containerPort: 2457, hostPort: 2457, protocol: 'udp' }],
    [
      { name: 'SERVER_NAME', value: 'Trakend Valheim', description: 'Server name' },
      { name: 'WORLD_NAME', value: 'TrakendWorld', description: 'World name' },
      { name: 'SERVER_PASS', value: '', description: 'Server password (min 5 chars)' },
    ],
    [{ containerPath: '/config', hostPath: '/mnt/appdata/valheim/config', description: 'Config' },
     { containerPath: '/data', hostPath: '/mnt/appdata/valheim/data', description: 'World data' }]),
  simple('terraria', 'Terraria Server', '🌳', 'Game Servers',
    'Dedicated Terraria server with TShock mod support',
    'ryshe/terraria:latest',
    [{ containerPort: 7777, hostPort: 7777, protocol: 'tcp' }],
    [{ name: 'WORLD_FILENAME', value: 'TrakendWorld.wld', description: 'World filename' }],
    [{ containerPath: '/root/.local/share/Terraria/Worlds', hostPath: '/mnt/appdata/terraria/worlds', description: 'Worlds' }]),
  simple('ark-se', 'ARK: Survival Evolved', '🦕', 'Game Servers',
    'Dedicated ARK: Survival Evolved server',
    'hermsi/ark-server:latest',
    [{ containerPort: 7777, hostPort: 7777, protocol: 'udp' }, { containerPort: 27015, hostPort: 27015, protocol: 'udp' }],
    [
      { name: 'SESSION_NAME', value: 'Trakend ARK Server', description: 'Server name' },
      { name: 'MAX_PLAYERS', value: '20', description: 'Max players' },
    ],
    [{ containerPath: '/ark', hostPath: '/mnt/appdata/ark', description: 'Server data' }],
    { resources: { cpuCores: 4, memoryMb: 8192 } }),
  simple('rust', 'Rust Server', '🔫', 'Game Servers',
    'Dedicated Rust game server',
    'didstopia/rust-server:latest',
    [{ containerPort: 28015, hostPort: 28015, protocol: 'udp' }, { containerPort: 28016, hostPort: 28016, protocol: 'tcp' }],
    [
      { name: 'RUST_SERVER_NAME', value: 'Trakend Rust', description: 'Server name' },
      { name: 'RUST_SERVER_MAXPLAYERS', value: '50', description: 'Max players' },
    ],
    [{ containerPath: '/steamcmd/rust', hostPath: '/mnt/appdata/rust', description: 'Server data' }],
    { resources: { cpuCores: 4, memoryMb: 8192 } }),
  simple('satisfactory', 'Satisfactory Server', '🏭', 'Game Servers',
    'Dedicated Satisfactory server with auto-save and backup',
    'wolveix/satisfactory-server:latest',
    [{ containerPort: 7777, hostPort: 7777, protocol: 'udp' }, { containerPort: 15000, hostPort: 15000, protocol: 'udp' }],
    [{ name: 'MAXPLAYERS', value: '4', description: 'Max players' }],
    [{ containerPath: '/config', hostPath: '/mnt/appdata/satisfactory', description: 'Server data' }],
    { resources: { cpuCores: 4, memoryMb: 8192 } }),
  simple('palworld', 'Palworld Server', '🐾', 'Game Servers',
    'Dedicated Palworld server with auto-updates',
    'thijsvanloef/palworld-server-docker:latest',
    [{ containerPort: 8211, hostPort: 8211, protocol: 'udp' }],
    [
      { name: 'PLAYERS', value: '16', description: 'Max players' },
      { name: 'SERVER_NAME', value: 'Trakend Palworld', description: 'Server name' },
      { name: 'ADMIN_PASSWORD', value: '', description: 'Admin password' },
    ],
    [{ containerPath: '/palworld', hostPath: '/mnt/appdata/palworld', description: 'Server data' }],
    { resources: { cpuCores: 4, memoryMb: 8192 } }),

  // ═══════════════════════════════════════
  // CLOUD & PRODUCTIVITY
  // ═══════════════════════════════════════
  simple('nextcloud', 'Nextcloud', '☁️', 'Cloud',
    'Self-hosted cloud storage — files, calendars, contacts, mail and collaboration',
    'nextcloud:latest',
    [{ containerPort: 80, hostPort: 8080, protocol: 'tcp' }],
    [
      { name: 'NEXTCLOUD_ADMIN_USER', value: 'admin', description: 'Admin username' },
      { name: 'NEXTCLOUD_ADMIN_PASSWORD', value: '', description: 'Admin password' },
    ],
    [
      { containerPath: '/var/www/html', hostPath: '/mnt/appdata/nextcloud/html', description: 'Nextcloud data' },
      { containerPath: '/var/www/html/data', hostPath: '/mnt/appdata/nextcloud/data', description: 'User data' },
    ]),
  simple('syncthing', 'Syncthing', '🔄', 'Cloud',
    'Continuous file synchronization across devices — no cloud required',
    'linuxserver/syncthing:latest',
    [{ containerPort: 8384, hostPort: 8384, protocol: 'tcp' }, { containerPort: 22000, hostPort: 22000, protocol: 'tcp' }],
    [{ name: 'PUID', value: '1000', description: 'User ID' }, { name: 'PGID', value: '1000', description: 'Group ID' }],
    [
      { containerPath: '/config', hostPath: '/mnt/appdata/syncthing', description: 'Config' },
      { containerPath: '/data', hostPath: '/mnt/sync', description: 'Sync data' },
    ]),
  simple('vaultwarden', 'Vaultwarden', '🔑', 'Cloud',
    'Lightweight Bitwarden-compatible password manager server',
    'vaultwarden/server:latest',
    [{ containerPort: 80, hostPort: 8090, protocol: 'tcp' }],
    [{ name: 'ADMIN_TOKEN', value: '', description: 'Admin panel token' }],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/vaultwarden', description: 'Data' }]),
  simple('immich', 'Immich', '📸', 'Cloud',
    'High-performance self-hosted photo and video management — Google Photos alternative',
    'ghcr.io/immich-app/immich-server:latest',
    [{ containerPort: 3001, hostPort: 2283, protocol: 'tcp' }],
    [
      { name: 'DB_HOSTNAME', value: 'immich-db', description: 'Database host' },
      { name: 'DB_USERNAME', value: 'immich', description: 'Database user' },
      { name: 'DB_PASSWORD', value: '', description: 'Database password' },
      { name: 'DB_DATABASE_NAME', value: 'immich', description: 'Database name' },
      { name: 'REDIS_HOSTNAME', value: 'immich-redis', description: 'Redis host' },
    ],
    [
      { containerPath: '/usr/src/app/upload', hostPath: '/mnt/appdata/immich/upload', description: 'Upload data' },
    ],
    { resources: { cpuCores: 4, memoryMb: 4096 } }),
  simple('filebrowser', 'File Browser', '📂', 'Cloud',
    'Web-based file manager with sharing, user management and built-in editor',
    'filebrowser/filebrowser:latest',
    [{ containerPort: 80, hostPort: 8091, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/srv', hostPath: '/mnt', description: 'Files root' },
      { containerPath: '/database/filebrowser.db', hostPath: '/mnt/appdata/filebrowser/filebrowser.db', description: 'Database' },
    ]),
  simple('gitea', 'Gitea', '🐙', 'Dev',
    'Lightweight self-hosted Git service — easy to install and maintain',
    'gitea/gitea:latest',
    [{ containerPort: 3000, hostPort: 3001, protocol: 'tcp' }, { containerPort: 22, hostPort: 2222, protocol: 'tcp' }],
    [],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/gitea', description: 'Gitea data' }]),
  simple('wiki-js', 'Wiki.js', '📖', 'Cloud',
    'Modern and powerful wiki app built on Node.js',
    'ghcr.io/requarks/wiki:2',
    [{ containerPort: 3000, hostPort: 3002, protocol: 'tcp' }],
    [
      { name: 'DB_TYPE', value: 'sqlite', description: 'Database type' },
      { name: 'DB_FILEPATH', value: '/data/wiki.sqlite', description: 'Database path' },
    ],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/wikijs', description: 'Wiki data' }]),

  // ═══════════════════════════════════════
  // NETWORKING & SECURITY
  // ═══════════════════════════════════════
  lsio('nginx-proxy-manager', 'Nginx Proxy Manager', '🔀', 'Network',
    'Easy-to-use reverse proxy with Let\'s Encrypt SSL, access lists and more',
    'nginx-proxy-manager',
    [
      { containerPort: 80, hostPort: 80, protocol: 'tcp' },
      { containerPort: 443, hostPort: 443, protocol: 'tcp' },
      { containerPort: 81, hostPort: 81, protocol: 'tcp' },
    ]),
  simple('traefik', 'Traefik', '🚦', 'Network',
    'Modern HTTP reverse proxy and load balancer with automatic HTTPS',
    'traefik:latest',
    [
      { containerPort: 80, hostPort: 80, protocol: 'tcp' },
      { containerPort: 443, hostPort: 443, protocol: 'tcp' },
      { containerPort: 8080, hostPort: 8089, protocol: 'tcp' },
    ],
    [{ name: 'TRAEFIK_API_INSECURE', value: 'true', description: 'Enable dashboard' }],
    [{ containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' }]),
  simple('pihole', 'Pi-hole', '🕳️', 'Network',
    'Network-wide ad blocking DNS server — block ads on all your devices',
    'pihole/pihole:latest',
    [
      { containerPort: 80, hostPort: 8000, protocol: 'tcp' },
      { containerPort: 53, hostPort: 53, protocol: 'tcp' },
      { containerPort: 53, hostPort: 53, protocol: 'udp' },
    ],
    [
      { name: 'WEBPASSWORD', value: '', description: 'Admin password' },
      { name: 'TZ', value: 'America/Chicago', description: 'Timezone' },
    ],
    [
      { containerPath: '/etc/pihole', hostPath: '/mnt/appdata/pihole', description: 'Pi-hole config' },
      { containerPath: '/etc/dnsmasq.d', hostPath: '/mnt/appdata/pihole/dnsmasq', description: 'DNS config' },
    ]),
  simple('adguard', 'AdGuard Home', '🛡️', 'Network',
    'Network-wide ad and tracker blocking DNS server with HTTPS filtering',
    'adguard/adguardhome:latest',
    [
      { containerPort: 80, hostPort: 3003, protocol: 'tcp' },
      { containerPort: 53, hostPort: 53, protocol: 'udp' },
      { containerPort: 3000, hostPort: 3004, protocol: 'tcp' },
    ],
    [],
    [
      { containerPath: '/opt/adguardhome/work', hostPath: '/mnt/appdata/adguard/work', description: 'Work dir' },
      { containerPath: '/opt/adguardhome/conf', hostPath: '/mnt/appdata/adguard/conf', description: 'Config' },
    ]),
  lsio('wireguard', 'WireGuard', '🔐', 'Network',
    'Fast, modern, secure VPN tunnel for private network access',
    'wireguard', [{ containerPort: 51820, hostPort: 51820, protocol: 'udp' }],
    [
      { name: 'SERVERURL', value: 'auto', description: 'Server URL or IP' },
      { name: 'PEERS', value: '3', description: 'Number of peer configs to generate' },
    ]),
  simple('tailscale', 'Tailscale', '🌐', 'Network',
    'Zero-config VPN based on WireGuard — connect all your devices securely',
    'tailscale/tailscale:latest',
    [],
    [
      { name: 'TS_AUTHKEY', value: '', description: 'Tailscale auth key from admin console' },
      { name: 'TS_HOSTNAME', value: 'trakend-os', description: 'Device hostname' },
    ],
    [{ containerPath: '/var/lib/tailscale', hostPath: '/mnt/appdata/tailscale', description: 'State' }]),
  simple('cloudflared', 'Cloudflare Tunnel', '🔒', 'Network',
    'Expose local services to the internet securely via Cloudflare Tunnel (Argo)',
    'cloudflare/cloudflared:latest',
    [],
    [{ name: 'TUNNEL_TOKEN', value: '', description: 'Cloudflare tunnel token' }],
    []),
  lsio('speedtest-tracker', 'Speedtest Tracker', '🏎️', 'Network',
    'Self-hosted internet speed test tracker with scheduled tests and history',
    'speedtest-tracker', [{ containerPort: 80, hostPort: 8092, protocol: 'tcp' }],
    [{ name: 'APP_KEY', value: '', description: 'Laravel app key (generate with base64:...)' }]),

  // ═══════════════════════════════════════
  // MONITORING & MANAGEMENT
  // ═══════════════════════════════════════
  simple('prometheus', 'Prometheus', '📊', 'Monitoring',
    'Metrics collection and alerting toolkit for monitoring infrastructure',
    'prom/prometheus:latest',
    [{ containerPort: 9090, hostPort: 9090, protocol: 'tcp' }],
    [],
    [{ containerPath: '/prometheus', hostPath: '/mnt/appdata/prometheus', description: 'Data' }]),
  simple('grafana', 'Grafana', '📈', 'Monitoring',
    'Beautiful dashboards and analytics for any database or metric source',
    'grafana/grafana:latest',
    [{ containerPort: 3000, hostPort: 3005, protocol: 'tcp' }],
    [
      { name: 'GF_SECURITY_ADMIN_USER', value: 'admin', description: 'Admin user' },
      { name: 'GF_SECURITY_ADMIN_PASSWORD', value: 'admin', description: 'Admin password' },
    ],
    [{ containerPath: '/var/lib/grafana', hostPath: '/mnt/appdata/grafana', description: 'Data' }]),
  simple('uptime-kuma', 'Uptime Kuma', '🟢', 'Monitoring',
    'Self-hosted monitoring tool like Uptime Robot — check website, TCP, Docker, DNS availability',
    'louislam/uptime-kuma:latest',
    [{ containerPort: 3001, hostPort: 3006, protocol: 'tcp' }],
    [],
    [{ containerPath: '/app/data', hostPath: '/mnt/appdata/uptime-kuma', description: 'Data' }]),
  simple('portainer', 'Portainer', '🐳', 'Management',
    'Full-featured Docker management UI — containers, images, volumes, networks',
    'portainer/portainer-ce:latest',
    [{ containerPort: 9443, hostPort: 9443, protocol: 'tcp' }, { containerPort: 9000, hostPort: 9000, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/data', hostPath: '/mnt/appdata/portainer', description: 'Data' },
      { containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' },
    ]),
  simple('watchtower', 'Watchtower', '🗼', 'Management',
    'Automatically update running Docker containers when new images are available',
    'containrrr/watchtower:latest',
    [],
    [
      { name: 'WATCHTOWER_CLEANUP', value: 'true', description: 'Remove old images' },
      { name: 'WATCHTOWER_SCHEDULE', value: '0 0 4 * * *', description: 'Check schedule (cron)' },
    ],
    [{ containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' }]),
  simple('dozzle', 'Dozzle', '📋', 'Management',
    'Realtime Docker log viewer in the browser — no setup required',
    'amir20/dozzle:latest',
    [{ containerPort: 8080, hostPort: 8093, protocol: 'tcp' }],
    [],
    [{ containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' }]),
  simple('homepage', 'Homepage', '🏡', 'Management',
    'Modern, fully-featured application dashboard with service integrations and widgets',
    'ghcr.io/gethomepage/homepage:latest',
    [{ containerPort: 3000, hostPort: 3007, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/app/config', hostPath: '/mnt/appdata/homepage', description: 'Config' },
      { containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' },
    ]),
  simple('homarr', 'Homarr', '🧭', 'Management',
    'Sleek, modern dashboard for your home server with drag-and-drop customization',
    'ghcr.io/homarr-labs/homarr:latest',
    [{ containerPort: 7575, hostPort: 7575, protocol: 'tcp' }],
    [],
    [{ containerPath: '/appdata', hostPath: '/mnt/appdata/homarr', description: 'Data' }]),

  // ═══════════════════════════════════════
  // DATABASES
  // ═══════════════════════════════════════
  simple('mariadb', 'MariaDB', '🗃️', 'Databases',
    'Fast, reliable MySQL-compatible relational database server',
    'mariadb:11',
    [{ containerPort: 3306, hostPort: 3306, protocol: 'tcp' }],
    [
      { name: 'MYSQL_ROOT_PASSWORD', value: '', description: 'Root password' },
      { name: 'MYSQL_DATABASE', value: 'default', description: 'Default database' },
    ],
    [{ containerPath: '/var/lib/mysql', hostPath: '/mnt/appdata/mariadb', description: 'Database files' }]),
  simple('postgres', 'PostgreSQL', '🐘', 'Databases',
    'Advanced open-source relational database with full SQL compliance',
    'postgres:16',
    [{ containerPort: 5432, hostPort: 5432, protocol: 'tcp' }],
    [
      { name: 'POSTGRES_PASSWORD', value: '', description: 'Superuser password' },
      { name: 'POSTGRES_DB', value: 'default', description: 'Default database' },
    ],
    [{ containerPath: '/var/lib/postgresql/data', hostPath: '/mnt/appdata/postgres', description: 'Database files' }]),
  simple('redis', 'Redis', '🔴', 'Databases',
    'In-memory data structure store — cache, message broker and database',
    'redis:7-alpine',
    [{ containerPort: 6379, hostPort: 6379, protocol: 'tcp' }],
    [],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/redis', description: 'Data' }]),
  simple('mongodb', 'MongoDB', '🍃', 'Databases',
    'NoSQL document database for modern applications',
    'mongo:7',
    [{ containerPort: 27017, hostPort: 27017, protocol: 'tcp' }],
    [
      { name: 'MONGO_INITDB_ROOT_USERNAME', value: 'admin', description: 'Admin username' },
      { name: 'MONGO_INITDB_ROOT_PASSWORD', value: '', description: 'Admin password' },
    ],
    [{ containerPath: '/data/db', hostPath: '/mnt/appdata/mongodb', description: 'Database files' }]),
  simple('influxdb', 'InfluxDB', '📉', 'Databases',
    'Time-series database for metrics, events, and real-time analytics',
    'influxdb:2',
    [{ containerPort: 8086, hostPort: 8086, protocol: 'tcp' }],
    [
      { name: 'DOCKER_INFLUXDB_INIT_USERNAME', value: 'admin', description: 'Admin user' },
      { name: 'DOCKER_INFLUXDB_INIT_PASSWORD', value: '', description: 'Admin password' },
      { name: 'DOCKER_INFLUXDB_INIT_ORG', value: 'trakend', description: 'Organization' },
      { name: 'DOCKER_INFLUXDB_INIT_BUCKET', value: 'default', description: 'Default bucket' },
    ],
    [{ containerPath: '/var/lib/influxdb2', hostPath: '/mnt/appdata/influxdb', description: 'Data' }]),
  simple('phpmyadmin', 'phpMyAdmin', '🗄️', 'Databases',
    'Web-based MySQL/MariaDB administration tool',
    'phpmyadmin:latest',
    [{ containerPort: 80, hostPort: 8094, protocol: 'tcp' }],
    [{ name: 'PMA_ARBITRARY', value: '1', description: 'Allow any server connection' }],
    []),
  simple('pgadmin', 'pgAdmin', '🐘', 'Databases',
    'Web-based PostgreSQL administration and development tool',
    'dpage/pgadmin4:latest',
    [{ containerPort: 80, hostPort: 8095, protocol: 'tcp' }],
    [
      { name: 'PGADMIN_DEFAULT_EMAIL', value: 'admin@trakend.local', description: 'Admin email' },
      { name: 'PGADMIN_DEFAULT_PASSWORD', value: '', description: 'Admin password' },
    ],
    [{ containerPath: '/var/lib/pgadmin', hostPath: '/mnt/appdata/pgadmin', description: 'Data' }]),

  // ═══════════════════════════════════════
  // HOME AUTOMATION
  // ═══════════════════════════════════════
  simple('homeassistant', 'Home Assistant', '🏠', 'Home',
    'Open source home automation — local control, privacy-first, 2000+ integrations',
    'homeassistant/home-assistant:latest',
    [{ containerPort: 8123, hostPort: 8123, protocol: 'tcp' }],
    [{ name: 'TZ', value: 'America/Chicago', description: 'Timezone' }],
    [{ containerPath: '/config', hostPath: '/mnt/appdata/homeassistant', description: 'Config' }],
    { resources: { cpuCores: 2, memoryMb: 1024 } }),
  simple('node-red', 'Node-RED', '🔴', 'Home',
    'Low-code programming for event-driven IoT and home automation flows',
    'nodered/node-red:latest',
    [{ containerPort: 1880, hostPort: 1880, protocol: 'tcp' }],
    [],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/nodered', description: 'Data' }]),
  simple('mosquitto', 'Eclipse Mosquitto', '🦟', 'Home',
    'Lightweight MQTT message broker for IoT and home automation',
    'eclipse-mosquitto:latest',
    [{ containerPort: 1883, hostPort: 1883, protocol: 'tcp' }, { containerPort: 9001, hostPort: 9001, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/mosquitto/config', hostPath: '/mnt/appdata/mosquitto/config', description: 'Config' },
      { containerPath: '/mosquitto/data', hostPath: '/mnt/appdata/mosquitto/data', description: 'Data' },
    ]),
  simple('zigbee2mqtt', 'Zigbee2MQTT', '📡', 'Home',
    'Bridge Zigbee devices to MQTT — no vendor lock-in',
    'koenkk/zigbee2mqtt:latest',
    [{ containerPort: 8080, hostPort: 8096, protocol: 'tcp' }],
    [{ name: 'TZ', value: 'America/Chicago', description: 'Timezone' }],
    [{ containerPath: '/app/data', hostPath: '/mnt/appdata/zigbee2mqtt', description: 'Data' }]),

  // ═══════════════════════════════════════
  // DEV TOOLS
  // ═══════════════════════════════════════
  lsio('code-server', 'Code Server', '💻', 'Dev',
    'VS Code in the browser — full IDE accessible from anywhere',
    'code-server', [{ containerPort: 8443, hostPort: 8443, protocol: 'tcp' }],
    [{ name: 'PASSWORD', value: '', description: 'Access password' }],
    [{ containerPath: '/workspace', hostPath: '/mnt/projects', description: 'Projects' }]),
  simple('jenkins', 'Jenkins', '🏗️', 'Dev',
    'Leading open source CI/CD automation server',
    'jenkins/jenkins:lts',
    [{ containerPort: 8080, hostPort: 8098, protocol: 'tcp' }, { containerPort: 50000, hostPort: 50000, protocol: 'tcp' }],
    [],
    [{ containerPath: '/var/jenkins_home', hostPath: '/mnt/appdata/jenkins', description: 'Jenkins home' }]),
  simple('drone', 'Drone CI', '🐝', 'Dev',
    'Container-native continuous delivery platform',
    'drone/drone:latest',
    [{ containerPort: 80, hostPort: 8099, protocol: 'tcp' }],
    [
      { name: 'DRONE_GITEA_SERVER', value: '', description: 'Gitea server URL' },
      { name: 'DRONE_RPC_SECRET', value: '', description: 'RPC secret' },
      { name: 'DRONE_SERVER_HOST', value: '', description: 'Drone server host' },
      { name: 'DRONE_SERVER_PROTO', value: 'http', description: 'Server protocol' },
    ],
    [{ containerPath: '/data', hostPath: '/mnt/appdata/drone', description: 'Data' }]),
  simple('n8n', 'n8n', '⚡', 'Dev',
    'Workflow automation tool — connect anything to everything',
    'n8nio/n8n:latest',
    [{ containerPort: 5678, hostPort: 5678, protocol: 'tcp' }],
    [],
    [{ containerPath: '/home/node/.n8n', hostPath: '/mnt/appdata/n8n', description: 'Data' }]),

  // ═══════════════════════════════════════
  // AI & ML
  // ═══════════════════════════════════════
  simple('ollama', 'Ollama', '🤖', 'AI',
    'Run large language models locally — Llama, Mistral, Gemma, Phi and more',
    'ollama/ollama:latest',
    [{ containerPort: 11434, hostPort: 11434, protocol: 'tcp' }],
    [],
    [{ containerPath: '/root/.ollama', hostPath: '/mnt/appdata/ollama', description: 'Models' }],
    { resources: { cpuCores: 8, memoryMb: 16384 } }),
  simple('open-webui', 'Open WebUI', '🌟', 'AI',
    'ChatGPT-style web interface for Ollama and OpenAI-compatible APIs',
    'ghcr.io/open-webui/open-webui:main',
    [{ containerPort: 8080, hostPort: 3008, protocol: 'tcp' }],
    [{ name: 'OLLAMA_BASE_URL', value: 'http://ollama:11434', description: 'Ollama API URL' }],
    [{ containerPath: '/app/backend/data', hostPath: '/mnt/appdata/open-webui', description: 'Data' }]),
  simple('stable-diffusion', 'Stable Diffusion WebUI', '🎨', 'AI',
    'AUTOMATIC1111 Stable Diffusion web UI for AI image generation',
    'ghcr.io/ai-dock/stable-diffusion-webui:latest',
    [{ containerPort: 7860, hostPort: 7860, protocol: 'tcp' }],
    [],
    [{ containerPath: '/workspace', hostPath: '/mnt/appdata/stable-diffusion', description: 'Models & outputs' }],
    { resources: { cpuCores: 8, memoryMb: 16384 } }),

  // ═══════════════════════════════════════
  // UTILITY
  // ═══════════════════════════════════════
  simple('duplicati', 'Duplicati', '💾', 'Backup',
    'Free encrypted cloud backup — supports S3, Google Drive, Azure, OneDrive and more',
    'linuxserver/duplicati:latest',
    [{ containerPort: 8200, hostPort: 8200, protocol: 'tcp' }],
    [{ name: 'PUID', value: '1000', description: 'User ID' }, { name: 'PGID', value: '1000', description: 'Group ID' }],
    [
      { containerPath: '/config', hostPath: '/mnt/appdata/duplicati', description: 'Config' },
      { containerPath: '/source', hostPath: '/mnt', description: 'Source data to back up' },
    ]),
  simple('netdata', 'Netdata', '📉', 'Monitoring',
    'Real-time infrastructure monitoring with zero configuration',
    'netdata/netdata:latest',
    [{ containerPort: 19999, hostPort: 19999, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/host/proc', hostPath: '/proc', description: '/proc' },
      { containerPath: '/host/sys', hostPath: '/sys', description: '/sys' },
      { containerPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock', description: 'Docker socket' },
    ]),
  lsio('smokeping', 'Smokeping', '💨', 'Monitoring',
    'Latency and packet loss monitoring with graphs — keep track of your network health',
    'smokeping', [{ containerPort: 80, hostPort: 8100, protocol: 'tcp' }]),
  lsio('librespeed', 'LibreSpeed', '🚀', 'Network',
    'Self-hosted internet speed test — HTML5 based, no Flash required',
    'librespeed', [{ containerPort: 80, hostPort: 8101, protocol: 'tcp' }]),
  simple('nginx', 'Nginx', '🌐', 'Network',
    'High-performance web server, reverse proxy and load balancer',
    'nginx:latest',
    [{ containerPort: 80, hostPort: 80, protocol: 'tcp' }, { containerPort: 443, hostPort: 443, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/etc/nginx', hostPath: '/mnt/appdata/nginx/config', description: 'Config' },
      { containerPath: '/usr/share/nginx/html', hostPath: '/mnt/appdata/nginx/html', description: 'Web root' },
    ]),
  simple('caddy', 'Caddy', '🏕️', 'Network',
    'Web server with automatic HTTPS — simple config, powerful features',
    'caddy:latest',
    [{ containerPort: 80, hostPort: 80, protocol: 'tcp' }, { containerPort: 443, hostPort: 443, protocol: 'tcp' }],
    [],
    [
      { containerPath: '/data', hostPath: '/mnt/appdata/caddy/data', description: 'Caddy data' },
      { containerPath: '/config', hostPath: '/mnt/appdata/caddy/config', description: 'Config' },
    ]),
  simple('changedetection', 'Change Detection', '👁️', 'Utility',
    'Monitor web pages for changes — get notified when content updates',
    'ghcr.io/dgtlmoon/changedetection.io:latest',
    [{ containerPort: 5000, hostPort: 5000, protocol: 'tcp' }],
    [],
    [{ containerPath: '/datastore', hostPath: '/mnt/appdata/changedetection', description: 'Data' }]),
  simple('paperless-ngx', 'Paperless-ngx', '📄', 'Utility',
    'Scan, index and archive all your physical documents digitally',
    'ghcr.io/paperless-ngx/paperless-ngx:latest',
    [{ containerPort: 8000, hostPort: 8102, protocol: 'tcp' }],
    [
      { name: 'PAPERLESS_SECRET_KEY', value: '', description: 'Secret key' },
      { name: 'PAPERLESS_OCR_LANGUAGE', value: 'eng', description: 'OCR language' },
    ],
    [
      { containerPath: '/usr/src/paperless/data', hostPath: '/mnt/appdata/paperless/data', description: 'Data' },
      { containerPath: '/usr/src/paperless/media', hostPath: '/mnt/appdata/paperless/media', description: 'Documents' },
      { containerPath: '/usr/src/paperless/consume', hostPath: '/mnt/appdata/paperless/consume', description: 'Inbox' },
    ]),
  simple('mealie', 'Mealie', '🍽️', 'Utility',
    'Self-hosted recipe manager and meal planner with shopping lists',
    'ghcr.io/mealie-recipes/mealie:latest',
    [{ containerPort: 9000, hostPort: 9925, protocol: 'tcp' }],
    [],
    [{ containerPath: '/app/data', hostPath: '/mnt/appdata/mealie', description: 'Data' }]),
  simple('stirling-pdf', 'Stirling PDF', '📑', 'Utility',
    'Self-hosted PDF manipulation tool — merge, split, convert, compress and more',
    'frooodle/s-pdf:latest',
    [{ containerPort: 8080, hostPort: 8103, protocol: 'tcp' }],
    [],
    []),
]
